<?php
/**
 * This file is part of EC-CUBE.
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 * https://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\MailMagazine\Tests\Web\Front;

use Eccube\Common\Constant;
use Eccube\Tests\Web\AbstractWebTestCase;

class MailMagazineEventOnRenderMypageChangeTest extends AbstractWebTestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function createFormData()
    {
        $faker = $this->getFaker();
        $tel = explode('-', $faker->phoneNumber);

        $email = $faker->safeEmail;
        $password = $faker->lexify('????????');
        $birth = $faker->dateTimeBetween;

        $form = array(
            'name' => array(
                'name01' => $faker->lastName,
                'name02' => $faker->firstName,
            ),
            'kana' => array(
                'kana01' => $faker->lastKanaName,
                'kana02' => $faker->firstKanaName,
            ),
            'company_name' => $faker->company,
            'zip' => array(
                'zip01' => $faker->postcode1(),
                'zip02' => $faker->postcode2(),
            ),
            'address' => array(
                'pref' => '5',
                'addr01' => $faker->city,
                'addr02' => $faker->streetAddress,
            ),
            'tel' => array(
                'tel01' => $tel[0],
                'tel02' => $tel[1],
                'tel03' => $tel[2],
            ),
            'fax' => array(
                'fax01' => $tel[0],
                'fax02' => $tel[1],
                'fax03' => $tel[2],
            ),
            'email' => $email,
            'password' => array(
                'first' => $password,
                'second' => $password,
            ),
            'birth' => array(
                'year' => $birth->format('Y'),
                'month' => $birth->format('n'),
                'day' => $birth->format('j'),
            ),
            'sex' => 1,
            'job' => 1,
            '_token' => 'dummy',
        );

        return $form;
    }

    public function testOnRenderMypageChange_NotLogin()
    {
        $this->client->request('GET',
            $this->app->url('mypage_change')
        );

        $this->assertFalse($this->client->getResponse()->isSuccessful());
    }

    public function testOnRenderMypageChange()
    {
        $this->User = $this->logIn();

        $crawler = $this->client->request('GET',
            $this->app->url('mypage_change')
        );

        $this->assertTrue($this->client->getResponse()->isSuccessful());
        $crawler->filter('#entry_mailmaga_flg')->html();
        $this->assertTrue(true);
    }

    public function testOnRenderMypageChange_Post()
    {
        $this->User = $this->logIn();

        $updateFlg = Constant::ENABLED;
        $form = $this->createFormData();
        $form['mailmaga_flg'] = $updateFlg;

        $this->client->request('POST',
            $this->app->url('mypage_change'),
            array(
                'entry' => $form,
            )
        );
        $MailCustomer = $this->app['eccube.plugin.mail_magazine.repository.mail_magazine_mailmaga_customer']
            ->findOneBy(array('customer_id' => $this->User->getId()));
        $this->actual = $MailCustomer->getMailmagaFlg();
        $this->expected = $updateFlg;
        $this->verify();
    }
}
