<?php

namespace Plugin\EccubePaymentLite3\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;

/**
 * EpsilonMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpsilonMemberRepository extends EntityRepository
{
    protected $app;

    public function setApp(\Eccube\Application $app) {
        $this->app = $app;
    }

    /**
     * Get Epsilon Member
     * @param $customer_id
     * @return mixed
     * @throws NonUniqueResultException
     */
    public function getEpsilonMemberByCustomerId($customer_id)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb ->select('e')
            ->from('\Plugin\EccubePaymentLite3\Entity\EpsilonMember', 'e')
            ->innerJoin('\Eccube\Entity\Customer', 'c', 'WITH', 'e.customer_id = c.id')
            ->andWhere('e.customer_id = :customer_id')
            ->setParameter('customer_id', $customer_id)
            ->orderBy('e.create_date', 'DESC');

        $epsilonMember = $qb
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();

        return $epsilonMember;
    }
}
