root: /html/
admin_dir: bkadmin/
tpl: /html/user_data/packages/default/
admin_tpl: /html/user_data/packages/admin/
image_path: /html/upload/save_image/
root_dir: /home/wp614605/biken-shop-mall.com/public_html
root_urlpath: null
template_code: mgtemplate
admin_route: bkadmin
user_data_route: user_data
public_path: /html
public_path_realdir: /home/wp614605/biken-shop-mall.com/public_html/html
image_save_realdir: /home/wp614605/biken-shop-mall.com/public_html/html/upload/save_image
image_temp_realdir: /home/wp614605/biken-shop-mall.com/public_html/html/upload/temp_image
user_data_realdir: /home/wp614605/biken-shop-mall.com/public_html/html/user_data
block_default_realdir: /home/wp614605/biken-shop-mall.com/public_html/src/Eccube/Resource/template/default/Block
block_realdir: /home/wp614605/biken-shop-mall.com/public_html/app/template/mgtemplate/Block
template_default_realdir: /home/wp614605/biken-shop-mall.com/public_html/src/Eccube/Resource/template/default
template_default_html_realdir: /home/wp614605/biken-shop-mall.com/public_html/html/template/default
template_admin_realdir: /home/wp614605/biken-shop-mall.com/public_html/src/Eccube/Resource/template/admin
template_admin_html_realdir: /home/wp614605/biken-shop-mall.com/public_html/html/template/admin
template_realdir: /home/wp614605/biken-shop-mall.com/public_html/app/template/mgtemplate
template_html_realdir: /home/wp614605/biken-shop-mall.com/public_html/html/template/mgtemplate
template_temp_realdir: /home/wp614605/biken-shop-mall.com/public_html/app/cache/eccube/template
csv_temp_realdir: /home/wp614605/biken-shop-mall.com/public_html/app/cache/eccube/csv
plugin_realdir: /home/wp614605/biken-shop-mall.com/public_html/app/Plugin
plugin_temp_realdir: /home/wp614605/biken-shop-mall.com/public_html/app/cache/plugin
plugin_html_realdir: /home/wp614605/biken-shop-mall.com/public_html/html/plugin
admin_urlpath: /html/template/admin
front_urlpath: /html/template/mgtemplate
image_save_urlpath: https://biken-shop-mall.com/html/upload/save_image
image_temp_urlpath: /html/upload/temp_image
user_data_urlpath: /html/user_data
plugin_urlpath: /html/plugin
