<?php



namespace Plugin\EccubePaymentLite3\Repository\Master;

use Doctrine\ORM\EntityRepository;

/**
 * ProductTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegularStatusRepository extends EntityRepository
{
}
