<?php
/*
 * This file is part of Receipt Pdf plugin
 *
 * Copyright (C) 2018 NinePoint Co. LTD. All Rights Reserved.
 *
 * Copyright (C) 2016 LOCKON CO.,LTD. All Rights Reserved.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\ReceiptPdf\Repository;

use Doctrine\ORM\EntityRepository;
use Eccube\Common\Constant;
use Eccube\Entity\Member;
use Plugin\ReceiptPdf\Entity\ReceiptPdf;

/**
 * ReceiptPdfRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceiptPdfRepository extends EntityRepository
{
    /**
     * Save admin history.
     *
     * @param array $arrData
     *
     * @return bool
     */
    public function save(array $arrData)
    {
        /**
         * @var Member $Member
         */
        $Member = $arrData['admin'];
        $em = $this->getEntityManager();
        try {
            $ReceiptPdf = $this->find($Member);
            if (!$ReceiptPdf) {
                $ReceiptPdf = new ReceiptPdf();
            }

            $ReceiptPdf->setId($Member->getId())
                ->setTitle($arrData['title'])
                ->setMessage1($arrData['message1'])
                ->setMessage2($arrData['message2'])
                ->setMessage3($arrData['message3'])
                ->setNote1($arrData['note1'])
                ->setNote2($arrData['note2'])
                ->setNote3($arrData['note3'])
                ->setCatalogDetail($arrData['catalog_detail'])
                ->setSpecificationFlg($arrData['specification_flg'])
                ->setReceiptFlg($arrData['receipt_flg'])
                ->setAddressNameFlg($arrData['address_name_flg'])
                ->setDelFlg(Constant::DISABLED);
            $em->persist($ReceiptPdf);
            $em->flush($ReceiptPdf);
        } catch (\Exception $e) {
            return false;
        }

        return true;
    }
}
