<?php
/*
* This file is part of EC-CUBE
*
* Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
* https://www.ec-cube.co.jp/
*
* For the full copyright and license information, please view the LICENSE
* file that was distributed with this source code.
*/

namespace Plugin\MailMagazine\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SendHistoryRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailMagazineSendHistoryRepository extends EntityRepository
{
    /**
     * dtb_send_historyに追加する.
     *
     * @param \Plugin\MailMagazine\Entity\MailMagazineSendHistory $sendHistory
     */
    public function createSendHistory(\Plugin\MailMagazine\Entity\MailMagazineSendHistory $sendHistory)
    {
        $em = $this->getEntityManager();
        $em->getConnection()->beginTransaction();
        try {
            $em->persist($sendHistory);
            $em->flush($sendHistory);

            $em->getConnection()->commit();
        } catch (\Exception $e) {
            $em->getConnection()->rollback();
            throw $e;
        }

        return true;
    }

    /**
     * dtb_send_historyを更新する.
     * createSendHistoryを呼び出すだけだが明示的に指定する.
     *
     * @param \Plugin\MailMagazine\Entity\MailMagazineSendHistory $sendHistory
     */
    public function updateSendHistory(\Plugin\MailMagazine\Entity\MailMagazineSendHistory $sendHistory)
    {
        return $this->createSendHistory($sendHistory);
    }
}
