<?php
/*
* This file is part of EC-CUBE
*
* Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
* https://www.ec-cube.co.jp/
*
* For the full copyright and license information, please view the LICENSE
* file that was distributed with this source code.
*/

namespace Plugin\MailMagazine\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MailmagaCustomerRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailmagaCustomerRepository extends EntityRepository
{
    /**
     * メルマガカスタマー情報を保存する.
     *
     * @param \Plugin\MailMagazine\Entity\MailmagaCustomer $MailmagaCustomer
     */
    public function save(\Plugin\MailMagazine\Entity\MailmagaCustomer $MailmagaCustomer)
    {
        $em = $this->getEntityManager();
        $em->persist($MailmagaCustomer);
        $em->flush($MailmagaCustomer);
    }
}
